[package]
name = "serial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpp = "0.5.9"
icp_2d = "0.1.0"
nannou = "0.19.0"
serialport = "4.3.0"
